# Always review the official build instructions before updating:
# https://wiki.qt.io/PySide2_GettingStarted#Building_PySide2

FROM centos:6

RUN yum install -y epel-release && \
    yum install -y deltarpm && \
    yum groupinstall "Development Tools" -y && \
    yum install -y https://centos6.iuscommunity.org/ius-release.rpm && \
    yum update -y && \
    yum install -y python35u python35u-libs python35u-devel python35u-pip && \
    yum install -y libxslt libxml2 libxml2-devel libxslt-devel cmake3 openssl && \
    yum install -y qt5-qtbase-devel && \
    yum install -y --skip-broken qt5*

RUN pip3.5 install wheel

RUN git clone --recursive --branch 5.6 https://codereview.qt-project.org/pyside/pyside-setup

ENTRYPOINT python3.5 \
           /pyside-setup/setup.py \
           bdist_wheel \
           --ignore-git \
           --qmake=/usr/lib64/qt5/bin/qmake-qt5 \
           --cmake=/usr/bin/cmake3
