from centos:7

RUN yum install -y epel-release
RUN yum groupinstall -y "Development Tools"
RUN yum install -y \
        python3-pip python3-devel wget \
        libxslt libxml2 libxml2-devel libxslt1-devel \
        qt5-qtbase-devel qt5-*

RUN pip install wheel

RUN wget http://www.cmake.org/files/v3.0/cmake-3.0.0.tar.gz && \
    gunzip cmake-3.0.0.tar.gz && \
    tar xf cmake-3.0.0.tar && \
    cd cmake-3.0.0 && \
    ./bootstrap && \
    gmake && \
    gmake install

RUN git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup

ENTRYPOINT python3 \
           /pyside-setup/setup.py \
           bdist_wheel \
           --ignore-git \
           --qmake=/usr/lib64/qt5/bin/qmake-qt5 \
           --cmake=/cmake-3.0.0/bin/cmake