# Always review the official build instructions before updating:
# https://wiki.qt.io/PySide2_GettingStarted#Building_PySide2

FROM centos:7

RUN yum install -y epel-release && \
    yum install -y deltarpm && \
    yum groupinstall "Development Tools" -y && \
    yum install -y python-libs python-devel python-pip && \
    yum install -y libxslt libxml2 libxml2-devel libxslt-devel cmake3 openssl && \
    yum install -y qt5-qtbase-devel && \
    yum install -y --skip-broken qt5*

# Set working directory
WORKDIR /workdir

# Install pip packages
RUN pip install wheel

# Clone PySide2 repository
RUN git clone --recursive --branch 5.6 https://codereview.qt-project.org/pyside/pyside-setup

# Build PySide2 wheel
ENTRYPOINT  \

            cd pyside-setup && \

            python setup.py \
                bdist_wheel \
                    --ignore-git \
                    --qmake=/usr/lib64/qt5/bin/qmake-qt5 \
                    --cmake=/usr/bin/cmake3
