from ubuntu:14.04

RUN apt-get update && \
    apt-get install -y \
        software-properties-common \
        python-pip python-dev \
        build-essential git libxml2 libxslt1.1 libxml2-dev libxslt1-dev wget && \
    add-apt-repository -y ppa:beineri/opt-qt561-trusty && \
    apt-get update && \
    apt-get install -y \
        qt56-meta-full

RUN wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
RUN tar -xf cmake-3.5.2-Linux-x86_64.tar.gz -C /opt
RUN source /opt/qt56/bin/qt56-env.sh  

RUN git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup /pyside-setup

ENTRYPOINT python \
           pyside-setup/setup.py \
           bdist_wheel \
           --ignore-git \
           --qmake=/opt/qt56/bin/qmake \
           --cmake=/opt/cmake-3.5.2-Linux-x86_64/bin/cmake
