from ubuntu:14.04

RUN apt-get update && \
    apt-get install -qq -y \
        software-properties-common \
        python3-pip python3-dev \
        build-essential git libxml2 libxslt1.1 libxml2-dev libxslt1-dev wget mesa-common-dev libglu1-mesa-dev && \
    add-apt-repository -y ppa:beineri/opt-qt561-trusty && \
    apt-get update && \
    apt-get install -qq -y \
        qt56-meta-full

RUN wget --quiet https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
RUN tar -xf cmake-3.5.2-Linux-x86_64.tar.gz -C /opt

RUN git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup /pyside-setup && \
    git -C $(pwd)/pyside-setup branch -a && \
    git -C $(pwd)/pyside-setup checkout remotes/origin/5.6

# /opt/qt56/bin/qt56-env.sh
ENV QT_BASE_DIR /opt/qt56
ENV QTDIR $QT_BASE_DIR
ENV PATH $QT_BASE_DIR/bin:$PATH
ENV LD_LIBRARY_PATH $QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH  # x86_64
# ENV LD_LIBRARY_PATH $QT_BASE_DIR/lib/i386-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH  # i386
ENV PKG_CONFIG_PATH $QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH



ENTRYPOINT  \
            # cat /opt/qt56/bin/qt56-env.sh > /pyside-setup/dist/qt56-env.sh && \
            python3 \
            pyside-setup/setup.py \
            bdist_wheel \
            --ignore-git \
            --qmake=/opt/qt56/bin/qmake \
            --cmake=/opt/cmake-3.5.2-Linux-x86_64/bin/cmake
