# Always review the official build instructions before updating:
# https://wiki.qt.io/PySide2_GettingStarted#Building_PySide2

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
                      python3-pip python3-dev \
                      build-essential git cmake libxml2 libxslt1.1 libxml2-dev libxslt1-dev \
                      software-properties-common python-software-properties && \
    add-apt-repository ppa:beineri/opt-qt562-xenial && \
    apt-get update && \
    apt-get install -qq -y \
        qt56-meta-full

RUN git clone --recursive --branch 5.6 https://codereview.qt-project.org/pyside/pyside-setup

ENTRYPOINT python3 \
           pyside-setup/setup.py \
           bdist_wheel \
           --ignore-git \
           --qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake \
           --cmake=/usr/bin/cmake
