FROM alpine:3.4

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    cmake \
    make \
    git \
    build-base \
    libxslt \
    libxml2 \
    qt5-qtbase-dev

RUN pip install wheel

RUN git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup /pyside-setup

ENTRYPOINT  \
            python \
            pyside-setup/setup.py \
            bdist_wheel \
            --ignore-git \
            --qmake=/usr/lib/qt5/bin/qmake \
            --cmake=/usr/bin/cmake