# Always review the official build instructions before updating:
# https://wiki.qt.io/PySide2_GettingStarted#Building_PySide2

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
                      python-pip python-dev \
                      build-essential git cmake libxml2 libxslt1.1 libxml2-dev libxslt1-dev wget

# RUN qt5-default qtbase5-dev \
#     qttools5-dev-tools libqt5clucene5 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5 libqt5feedback5 libqt5gui5 libqt5help5 libqt5multimedia5 libqt5network5 libqt5opengl5 libqt5opengl5-dev libqt5organizer5 libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5quick5 libqt5quickwidgets5 libqt5script5 libqt5scripttools5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webkit5 libqt5widgets5 libqt5xml5 libqt5xmlpatterns5 libqt5xmlpatterns5-dev

RUN wget http://download.qt-project.org/official_releases/qt/5.6/5.6.1/qt-opensource-linux-x64-5.6.1.run && \
    chmod +x qt-opensource-linux-x64-5.6.1.run && \
    ./qt-opensource-linux-x64-5.6.1.run

RUN git clone --recursive --branch 5.6 https://codereview.qt-project.org/pyside/pyside-setup

ENTRYPOINT python \
           pyside-setup/setup.py \
           bdist_wheel \
           --ignore-git \
           --qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake \
           --cmake=/usr/bin/cmake
